/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Aswin
 */
public class advanalytics extends javax.swing.JFrame {

    /**
     * Creates new form advanalytics
     */
    String url = "jdbc:oracle:thin:@localhost:1521:orcl2";
    String userName = "SYSTEM";
    String password = "sys";
    public advanalytics() {
        initComponents();
        agePanel.setVisible(false);
        resultDes.setVisible(false);
        //aInpAge1.setVisible(false);
        //aInpAge2.setVisible(false);
        //abutton.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        agePanel = new javax.swing.JPanel();
        aAbsAge = new javax.swing.JRadioButton();
        aRangeAge = new javax.swing.JRadioButton();
        resultDes = new javax.swing.JLabel();
        aMaleRad = new javax.swing.JRadioButton();
        aFemaleRad = new javax.swing.JRadioButton();
        aAll = new javax.swing.JRadioButton();
        aTransgenderRad = new javax.swing.JRadioButton();
        abutton = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        aInpAge1 = new javax.swing.JTextField();
        aInpAge2 = new javax.swing.JTextField();
        aInpLabel1 = new javax.swing.JLabel();
        aInpLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        agerad = new javax.swing.JRadioButton();
        staterad = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agePanel.setBackground(new java.awt.Color(51, 255, 255));

        buttonGroup2.add(aAbsAge);
        aAbsAge.setText("Absolute Age");
        aAbsAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAbsAgeActionPerformed(evt);
            }
        });

        buttonGroup2.add(aRangeAge);
        aRangeAge.setText("Range Age");
        aRangeAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aRangeAgeActionPerformed(evt);
            }
        });

        resultDes.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        resultDes.setText("as");

        buttonGroup3.add(aMaleRad);
        aMaleRad.setText("Only male");
        aMaleRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMaleRadActionPerformed(evt);
            }
        });

        buttonGroup3.add(aFemaleRad);
        aFemaleRad.setText("Female");
        aFemaleRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aFemaleRadActionPerformed(evt);
            }
        });

        buttonGroup3.add(aAll);
        aAll.setText("All");

        buttonGroup3.add(aTransgenderRad);
        aTransgenderRad.setText("Transgender");

        abutton.setText("ANALYSIS");
        abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abuttonActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        aInpAge2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        aInpAge2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aInpAge2ActionPerformed(evt);
            }
        });

        aInpLabel1.setText(" ");

        aInpLabel2.setText(" ");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout agePanelLayout = new javax.swing.GroupLayout(agePanel);
        agePanel.setLayout(agePanelLayout);
        agePanelLayout.setHorizontalGroup(
            agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agePanelLayout.createSequentialGroup()
                .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(aMaleRad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aFemaleRad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aTransgenderRad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aAll))
                    .addGroup(agePanelLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aInpLabel1)
                            .addGroup(agePanelLayout.createSequentialGroup()
                                .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(aInpAge1)
                                    .addComponent(aAbsAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(agePanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(aRangeAge)
                                        .addGap(173, 173, 173)
                                        .addComponent(jLabel1))
                                    .addGroup(agePanelLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(aInpLabel2)
                                            .addComponent(aInpAge2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, agePanelLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(resultDes, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, agePanelLayout.createSequentialGroup()
                            .addGap(349, 349, 349)
                            .addComponent(abutton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agePanelLayout.setVerticalGroup(
            agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aMaleRad)
                    .addComponent(aFemaleRad)
                    .addComponent(aAll)
                    .addComponent(aTransgenderRad))
                .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aAbsAge)
                            .addComponent(aRangeAge)))
                    .addGroup(agePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)))
                .addGap(32, 32, 32)
                .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aInpAge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aInpAge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agePanelLayout.createSequentialGroup()
                        .addGroup(agePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aInpLabel1)
                            .addComponent(aInpLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abutton)
                        .addGap(74, 74, 74)
                        .addComponent(resultDes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(agePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(153, 153, 153))
        );

        agerad.setBackground(new java.awt.Color(102, 255, 51));
        buttonGroup1.add(agerad);
        agerad.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        agerad.setText("AGE");
        agerad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageradActionPerformed(evt);
            }
        });

        staterad.setBackground(new java.awt.Color(102, 255, 102));
        buttonGroup1.add(staterad);
        staterad.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        staterad.setText("STATE");
        staterad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateradActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(agerad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(staterad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(agePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agerad)
                    .addComponent(staterad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(agePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageradActionPerformed
        // TODO add your handling code here:
        agePanel.setVisible(true);
        //abutton.setVisible(true);
        //age.setVisible(true);
    }//GEN-LAST:event_ageradActionPerformed

    private void stateradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateradActionPerformed

    private void aRangeAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aRangeAgeActionPerformed
        // TODO add your handling code here:
        aInpAge2.setVisible(true);
        aInpLabel1.setText("enter start age");
        aInpLabel2.setText("enter end age");
    }//GEN-LAST:event_aRangeAgeActionPerformed

    private void aMaleRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMaleRadActionPerformed
        // TODO add your handling code here:
        abutton.setVisible(true);
    }//GEN-LAST:event_aMaleRadActionPerformed

    private void aFemaleRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aFemaleRadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aFemaleRadActionPerformed

    private void aAbsAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAbsAgeActionPerformed
        // TODO add your handling code here:
       aInpAge2.setVisible(false);
       aInpLabel2.setText(null);
       aInpLabel1.setText("enter age");
    }//GEN-LAST:event_aAbsAgeActionPerformed

    private void abuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abuttonActionPerformed
        // TODO add your handling code here:
        String query;
        String gender;
        /*if(aAll.isSelected())
        {
            query="select count(*) from person";
        }
        */
        if(aMaleRad.isSelected())
        {
            gender="m";
        }
        else if(aFemaleRad.isSelected())
        {
            gender="f";
        }
        else //if(aTransgenderRad.isSelected())
        {
            gender="t";
        }
        try {
                Connection con = DriverManager.getConnection(url, userName, password);
                Class.forName("oracle.jdbc.driver.OracleDriver");
                if(aAll.isSelected())
                {
                    query="select count(*) from person where status =1";
                    resultDes.setText("total persons present in this age group is ");
                }
                else
                {
                    query="select count(*) from person where gender='"+gender+"' and status =1";
                    resultDes.setText("total "+gender.toUpperCase()+" present in this age group is ");
                }
                if(aAbsAge.isSelected())
                {
                    query=query+" and floor((sysdate-dob)/365) ="+Integer.parseInt(aInpAge1.getText().trim())+" ";
                }
                else
                {
                    query=query+" and floor((sysdate-dob)/365) between "+Integer.parseInt(aInpAge1.getText().trim())+ " and "+Integer.parseInt(aInpAge1.getText().trim());
                }
                ResultSet rs;
                Statement stmt;
                stmt = con.createStatement();
                rs = stmt.executeQuery(query);
                rs.next();
                resultDes.setVisible(true);
                result.setText(rs.getString(1));
                con.close();
                
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_abuttonActionPerformed

    private void aInpAge2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aInpAge2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aInpAge2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(advanalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(advanalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(advanalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(advanalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new advanalytics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aAbsAge;
    private javax.swing.JRadioButton aAll;
    private javax.swing.JRadioButton aFemaleRad;
    private javax.swing.JTextField aInpAge1;
    private javax.swing.JTextField aInpAge2;
    private javax.swing.JLabel aInpLabel1;
    private javax.swing.JLabel aInpLabel2;
    private javax.swing.JRadioButton aMaleRad;
    private javax.swing.JRadioButton aRangeAge;
    private javax.swing.JRadioButton aTransgenderRad;
    private javax.swing.JButton abutton;
    private javax.swing.JPanel agePanel;
    private javax.swing.JRadioButton agerad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel result;
    private javax.swing.JLabel resultDes;
    private javax.swing.JRadioButton staterad;
    // End of variables declaration//GEN-END:variables
}
