/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_project;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Aswin
 */
public class editPerson extends javax.swing.JFrame {

    /**
     * Creates new form editPerson
     */
    String url = "jdbc:oracle:thin:@localhost:1521:orcl2";
    String userName = "SYSTEM";
    String password = "sys";
    int editFlag=0;
    ResultSet rs;
    public editPerson() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        qualification = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        searchBotton = new javax.swing.JButton();
        dob = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        mls = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        father = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mother = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("DOB");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 80, -1));
        getContentPane().add(qualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 110, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("person id");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("STATUS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 131, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("MARTIAL STATUS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 170, 20));

        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        getContentPane().add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 110, -1));

        searchBotton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchBotton.setText("search");
        searchBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBottonActionPerformed(evt);
            }
        });
        getContentPane().add(searchBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 19, 110, -1));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 110, -1));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("FATHER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 100, -1));
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 110, -1));
        getContentPane().add(mls, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 110, -1));

        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 110, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("MOTHER");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 110, -1));
        getContentPane().add(father, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 256, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("PERSON ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("QUALIFICATION");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, -1));
        getContentPane().add(mother, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 294, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("GENDER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("STATE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 130, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 110, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/b2.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -210, 950, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed

    private void searchBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBottonActionPerformed
        // TODO add your handling code here:
        if(search.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "enter state id");
        }
        else
        {
            try {
                Connection con = DriverManager.getConnection(url, userName, password);
                Class.forName("oracle.jdbc.driver.OracleDriver");
                //String query="select * from person where id= '"+search.getText().trim()+"' ";
                String query="select * from person where id = '"+search.getText().trim()+"'";
                
                Statement stmt;
                stmt = con.createStatement();
                rs = stmt.executeQuery(query);
                if(rs.next())
                {
                    pid.setText(rs.getString(1));
                    pid.setEditable(false);
                    pname.setText(rs.getString(2));
                    gender.setText(rs.getString(3));
                    java.util.Date date =rs.getObject(4, Date.class);
                    dob.setText(date.toString());
                    mls.setText(rs.getString(5));
                    father.setText(rs.getString(6));
                    mother.setText(rs.getString(7));
                    qualification.setText(rs.getString(8));
                    state.setText(rs.getString(9));
                    status.setText(rs.getString(10));
                    editFlag=1;

                }
                else
                {
                    JOptionPane.showMessageDialog(null, "person id is not present");
                }
                con.close();

            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_searchBottonActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(editFlag==1)
        {
            try
            {
            String query;
            PreparedStatement stmt;
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection(url, userName, password);
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date = formatter.parse(dob.getText().trim());
            long ms =date.getTime();
            java.sql.Date sdate=new java.sql.Date(ms);
            if(father.getText().isEmpty()&&mother.getText().isEmpty())
            {
                query="update person set name = ?, gender=?, dob=?, martial_status=?, qualification=?, state=?, status=?  where id=?";
                stmt=con.prepareStatement(query);
                stmt.setString(8, search.getText().trim());
            }
            else if(father.getText().isEmpty())
            {
                query="update person set name = ?, gender=?, dob=?, martial_status=?, qualification=?, state=?, status=?, mother=? where id=?";
                stmt=con.prepareStatement(query);
                stmt.setString(8, mother.getText().trim());
                stmt.setString(9, search.getText().trim());
            }
            else if(mother.getText().isEmpty())
            {
                query="update person set name = ?, gender=?, dob=?, martial_status=?, qualification=?, state=?, status=?, father=? where id=?";
                stmt=con.prepareStatement(query);
                stmt.setString(8, father.getText().trim());
                stmt.setString(9, search.getText().trim());
            }
            else
            {
                query="update person set name = ?, gender=?, dob=?, martial_status=?, qualification=?, state=?, status=?, father=?, mother=? where id=?";
                stmt=con.prepareStatement(query);
                stmt.setString(8, father.getText().trim());
                stmt.setString(9, mother.getText().trim());
                stmt.setString(10, search.getText().trim());
            }
            stmt.setString(1, pname.getText().trim());
            stmt.setString(2, gender.getText().trim());
            stmt.setDate(3, sdate);
            stmt.setString(4, mls.getText().trim());
            stmt.setString(5, qualification.getText().trim());
            stmt.setString(6, state.getText().trim());
            stmt.setString(7, status.getText().trim());
            int res = stmt.executeUpdate();
            if(res==1)
                JOptionPane.showMessageDialog(null, "updated");
            con.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "please select person using search");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(editFlag==1)
        {
            String query="delete from person where id = '"+search.getText().trim()+"'";
            try
            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection(url, userName, password);
                Statement stmt;
                stmt = con.createStatement();
                rs = stmt.executeQuery(query);
                //if(rs.next())
                    JOptionPane.showMessageDialog(null, search.getText().trim()+" is deleted");
                clearLog();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "please select person using search");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    void clearLog()
    {
        search.setText(null);
        pid.setText(null);
        pname.setText(null);
        gender.setText(null);
        dob.setText(null);
        mls.setText(null);
        father.setText(null);
        mother.setText(null);
        qualification.setText(null);
        state.setText(null);
        status.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editPerson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dob;
    private javax.swing.JTextField father;
    private javax.swing.JTextField gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mls;
    private javax.swing.JTextField mother;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField qualification;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchBotton;
    private javax.swing.JTextField state;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
