/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_project;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ELCOT
 */
public class helpme extends javax.swing.JFrame {

    /**
     * Creates new form helpme
     */
    public helpme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WANT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        GO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 626));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(WANT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 250, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("I WANT TO.....");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 200, 40));

        GO.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        GO.setText("GO");
        GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOActionPerformed(evt);
            }
        });
        getContentPane().add(GO, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/ask.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 964, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOActionPerformed
        // TODO add your handling code here:
        String want=WANT.getText().trim();
        int w1=want.indexOf("birth");
        int w2=want.indexOf("death");
        int w3=want.indexOf("view");
        int w4=want.indexOf("marriage");
        int w5=want.indexOf("police");
        int w6=want.indexOf("ambulance");
        if(w1!=-1)
        {
              new bw().setVisible(true);
              
        }
        else if(w2!=-1)
        {
              new bw2().setVisible(true);
              
        }
         else if(w3!=-1)
        {
              new bw3().setVisible(true);
              
        }
        else   if(w4!=-1)
        {
              new bw4().setVisible(true);
              
        }
        else   if(w5!=-1)
        {
              new bw5().setVisible(true);
              
        }
        else if(w6!=-1)
        {
              new bw6().setVisible(true);
              
        }
        else
        {
            new result().setVisible(true);
        }
        
    }//GEN-LAST:event_GOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(helpme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(helpme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(helpme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(helpme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new helpme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GO;
    private javax.swing.JTextField WANT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
